# local, DEV, PROD 공통 설정
spring:
  profiles:
    default: local

---
# LOCAL
spring:
  profiles:
    group:
      local:
        - local_conf
        - local_db


---
# DEV
spring:
  profiles:
    group:
      dev:
        - dev_conf
        - dev_db

---
## PROD 1
spring:
  profiles:
    group:
      prod1:
        - prod_conf
        - prod_db
        - prod_port1

---
## PROD 2
spring:
  profiles:
    group:
      prod2:
        - prod_conf
        - prod_db
        - prod_port2


# 설정
---
# LOCAL 설정
spring:
  config:
    activate:
      on-profile: "local_conf"
server:
  port: 8204
---
# DEV 설정
spring:
  config:
    activate:
      on-profile: "dev_conf"


---
# PROD 공통 설정
spring:
  config:
    activate:
      on-profile: "prod_conf"
logging:
  level:
    root: info



# DATA BASE
---
# LOCAL DB
spring:
  config:
    activate:
      on-profile: "local_db"
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create # Application 실행 시점에 Table 초기화
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

---
# DEV DB
spring:
  config:
    activate:
      on-profile: "dev_db"
  datasource:
    url: "jdbc:mysql://"
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        # format_sql: true

logging.level:
  org.hibernate.SQL: debug
---
# PROD DB
spring:
  config:
    activate:
      on-profile: "prod_db"
  datasource:
    url: "jdbc:mysql:"
    username: ""
    password: ""


#PROD PORT
---
spring:
  config:
    activate:
      on-profile: "prod_port1"
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "prod_port2"
server:
  port: 8082
